import React, { useState } from 'react'
import { Link, useNavigate, Navigate } from 'react-router-dom'
import { Icon } from '@/components/Icon'
import { Avatar, Empty } from '@/components/ui'
import { JoinForm, SignInForm, SkinProfileForm } from '@/components/forms'
import { useStore } from '@/store/store'
import { rewardById } from '@/data/rewards'
import { productById, money } from '@/data/products'
import { n, fmtDate, ago } from '@/lib/format'

const Head = ({ title, right }: { title: string; right?: React.ReactNode }) => { const nav = useNavigate(); return <div className="screen-head"><button className="icon-btn" onClick={() => nav(-1)}><Icon name="chevron-left" /></button><h1 style={{ fontSize: 26 }}>{title}</h1>{right ?? <span style={{ width: 38 }} />}</div> }

export function AppProfile() {
  const { state, d } = useStore(); const m = state.member
  if (!m) return <div className="screen"><div className="screen-head"><h1>Profile</h1></div><div className="app-card"><h3 style={{ fontSize: 22, fontFamily: 'var(--font-display)', fontWeight: 500 }}>Sign in to Glow Club</h3><p className="small muted" style={{ margin: '6px 0 14px' }}>Your points, orders and routine, synced everywhere.</p><SignInForm onDone={() => {}} /><p className="small text-center" style={{ marginTop: 12 }}>New here? <Link to="/app/join" className="copper">Join Glow Club</Link></p></div></div>
  const active = state.redemptions.filter(r => r.status === 'approved' || r.status === 'pending')
  return <div className="screen">
    <div className="screen-head"><span className="app-logo">LUMIVA<small>CIRCLE</small></span><Link to="/app/profile/settings" className="icon-btn"><Icon name="settings" /></Link></div>
    <h1 style={{ fontSize: 30, marginBottom: 12 }}>My Membership</h1>
    <div className="member-card"><span className="lbl">Radiance</span><div className="tier">{d.tier.short.toUpperCase()}</div><div className="meta"><div><small>Member since</small>{new Date(m.joinedAt).toLocaleDateString('en-SG', { month: 'short', year: 'numeric' })}</div><div><small>Member ID</small>{m.memberId}</div></div></div>
    <div className="app-card between"><div><span className="tiny muted" style={{ letterSpacing: '.12em', textTransform: 'uppercase' }}>Points balance</span><div className="serif tnum" style={{ fontSize: 34, lineHeight: 1 }}>{n(d.balance)} <Icon name="sun" className="icon-sm copper" /></div></div><Link to="/app/profile/settings" style={{ textAlign: 'center', fontSize: 10.5, color: 'var(--ink-3)' }}><Icon name="qr" className="icon-lg" style={{ margin: '0 auto' }} />Scan to earn</Link></div>
    <div className="app-card"><span className="tiny muted" style={{ letterSpacing: '.12em', textTransform: 'uppercase' }}>Your tier benefits</span><div className="benefits-3" style={{ marginTop: 6 }}>{d.tier.benefits.slice(0, 3).map((b, i) => <div key={b}><Icon name={['gift', 'sparkle', 'clock'][i]} />{b}</div>)}</div></div>
    <div className="app-card"><span className="tiny muted" style={{ letterSpacing: '.12em', textTransform: 'uppercase' }}>Your activity summary</span><div className="grid" style={{ gridTemplateColumns: '1fr 1fr 1fr', marginTop: 8, gap: 8 }}><div><small className="tiny muted">Earned</small><div className="tnum" style={{ fontSize: 18, fontWeight: 600 }}>{n(d.earned)} pts</div></div><div><small className="tiny muted">Redeemed</small><div className="tnum" style={{ fontSize: 18, fontWeight: 600 }}>{n(d.redeemed)} pts</div></div><div><small className="tiny muted">Streak shields</small><div className="tnum" style={{ fontSize: 18, fontWeight: 600 }}>{state.streakShields}</div></div></div></div>
    {active.length > 0 && <div className="app-card"><h3 style={{ marginBottom: 6 }}>Ready to use</h3>{active.map(r => { const rw = rewardById(r.rewardId)!; return <div key={r.id} className="app-row"><img src={rw.image} alt="" style={{ width: 44, height: 44, borderRadius: 8, objectFit: 'cover' }} /><div><b>{rw.name}</b><small>Code {r.code}</small></div><span className={`pill tiny end ${r.status === 'pending' ? 'pill-gold' : 'pill-success'}`}>{r.status === 'pending' ? 'pending approval' : 'ready'}</span></div> })}</div>}
    <div className="app-card" style={{ padding: '4px 14px' }}>
      {[['/app/profile/history', 'Point History', 'sun'], ['/app/profile/saved', 'Saved Items & Rewards', 'heart'], ['/app/profile/orders', 'Orders', 'bag'], ['/app/profile/addresses', 'Addresses & Payment', 'home'], ['/app/spin', 'Glow Spin', 'compass'], ['/app/profile/referrals', 'Referrals', 'users'], ['/app/achievements', 'Achievements', 'medal'], ['/app/profile/skin', 'Skin Profile', 'face'], ['/app/profile/settings', 'Privacy & Settings', 'settings'], ['/help', 'Help Centre', 'info'], ['/help#terms', 'Terms', 'lock']].map(([to, l, i]) => <Link key={l} to={to} className="app-list-link"><Icon name={i} />{l}<Icon name="chevron" className="icon-sm" /></Link>)}
    </div>
    <div className="install-hint"><Icon name="download" className="icon-sm" /> Add Glow Club to your home screen: Share → Add to Home Screen.</div>
  </div>
}
export function AppHistory() {
  const { state, d } = useStore(); if (!state.member) return <Navigate to="/app/profile" replace />
  return <div className="screen"><Head title="Point History" /><div className="grid" style={{ gridTemplateColumns: '1fr 1fr 1fr', gap: 8, marginBottom: 12 }}><div className="stat"><b className="tnum" style={{ fontSize: 22 }}>{n(d.balance)}</b><small>Balance</small></div><div className="stat"><b className="tnum" style={{ fontSize: 22 }}>{n(d.held)}</b><small>Held</small></div><div className="stat"><b className="tnum" style={{ fontSize: 22 }}>{n(d.expiring)}</b><small>Expiring 90d</small></div></div><div className="app-card"><ul className="ledger">{[...state.ledger].reverse().map(e => <li key={e.id}><div><b className="small">{e.note}</b><p className="tiny muted">{fmtDate(e.ts)}</p></div><span className={`amt ${e.type === 'pending' ? 'pend' : e.points > 0 ? 'pos' : 'neg'}`}>{e.points > 0 ? '+' : ''}{n(e.points)}</span></li>)}</ul></div></div>
}
export function AppReferrals() {
  const { state, actions } = useStore(); const [name, setName] = useState(''); const [email, setEmail] = useState(''); if (!state.member) return <Navigate to="/app/profile" replace />
  return <div className="screen"><Head title="Referrals" /><div className="app-card"><b className="small">Invite a friend · +500 pts</b><p className="tiny muted" style={{ margin: '4px 0 10px' }}>Points arrive after their first order. Your code: <b>{state.member.referralCode}</b></p><div className="stack"><input className="input" placeholder="Friend's name" value={name} onChange={e => setName(e.target.value)} /><input className="input" placeholder="Email" value={email} onChange={e => setEmail(e.target.value)} /><button className="btn btn-primary" disabled={!name || !email} onClick={() => { actions.refer(name, email); setName(''); setEmail('') }}>Send invite</button></div></div><div className="app-card">{state.referrals.map(r => <div key={r.id} className="app-row"><Avatar initials={r.name.split(' ').map(x => x[0]).join('')} /><div><b>{r.name}</b><small>{ago(r.ts)}</small></div><div className="end"><span className={`pill tiny ${r.status === 'ordered' ? 'pill-success' : 'pill-muted'}`}>{r.status === 'ordered' ? '+500' : r.status}</span>{r.status !== 'ordered' && <button className="btn btn-sm btn-light" onClick={() => actions.simulateReferralOrder(r.id)}>Simulate</button>}</div></div>)}{!state.referrals.length && <p className="small muted">No invitations yet.</p>}</div></div>
}
export function AppOrders() {
  const { state } = useStore(); if (!state.member) return <Navigate to="/app/profile" replace />
  return <div className="screen"><Head title="Orders" />{state.orders.length ? state.orders.map(o => <div key={o.id} className="app-card"><div className="between"><b className="small tnum">{o.id}</b><span className={`pill tiny ${o.status === 'delivered' ? 'pill-success' : 'pill-gold'}`}>{o.status}</span></div><div className="order-items">{o.items.map(i => <img key={i.productId + (i.gift ? 'g' : '')} src={productById(i.productId)?.image} alt="" />)}</div><div className="between tiny muted" style={{ marginTop: 8 }}><span>{fmtDate(o.ts)}</span><span><b style={{ color: 'var(--ink)' }}>{money(o.total)}</b> · +{n(o.pointsEarned)} pts</span></div></div>) : <Empty title="No orders yet" action={<Link to="/app/shop" className="btn btn-primary">Shop</Link>} />}</div>
}
export function AppSettings() {
  const { state, actions } = useStore(); const m = state.member; if (!m) return <Navigate to="/app/profile" replace />
  const T = ({ k, label, sub }: { k: keyof typeof m.consent; label: string; sub: string }) => <div className="switch"><div>{label}<small>{sub}</small></div><button className={`toggle ${m.consent[k] ? 'on' : ''}`} onClick={() => actions.updateMember({ consent: { ...m.consent, [k]: !m.consent[k] } })} /></div>
  return <div className="screen"><Head title="Settings" /><div className="app-card"><b className="small">Privacy & communication</b><T k="publicActivity" label="Show my wins publicly" sub={`As “${m.firstName} ${m.lastName[0]}.” for verified events only`} /><T k="push" label="Push notifications" sub="Reorder reminders, missions, rewards" /><T k="marketing" label="Offers and tips" sub="Email and SMS, optional" /></div><div className="app-card"><b className="small">Account</b><p className="tiny muted" style={{ margin: '4px 0 10px' }}>{m.email} · {m.mobile}</p><div className="row"><Link to="/account/preferences" className="btn btn-sm btn-secondary">Export data</Link><button className="btn btn-sm btn-light" onClick={() => actions.signOut()}>Sign out</button></div></div><div className="app-card"><b className="small">Concept build tools</b><p className="tiny muted" style={{ margin: '4px 0 10px' }}>Reset everything on this device.</p><button className="btn btn-sm btn-light" onClick={() => actions.reset()}>Reset demo data</button></div></div>
}
export function AppSkinProfile() { const nav = useNavigate(); const { state } = useStore(); if (!state.member) return <Navigate to="/app/join" replace />; return <div className="screen"><Head title="Skin Profile" /><div className="app-card"><SkinProfileForm onDone={() => nav('/app/profile')} /></div></div> }
export function AppJoin() { const nav = useNavigate(); const { state } = useStore(); if (state.member) return <Navigate to="/app/rewards" replace />; return <div className="screen"><Head title="Join Glow Club" /><p className="small muted" style={{ marginBottom: 12 }}>Free forever. 500 welcome points and 1-for-1 on your first eligible order.</p><JoinForm compact onDone={() => nav('/app/rewards')} /><p className="small text-center" style={{ marginTop: 12 }}>Already a member? <Link to="/app/sign-in" className="copper">Sign in</Link></p></div> }
export function AppSignIn() { const nav = useNavigate(); const { state } = useStore(); if (state.member) return <Navigate to="/app" replace />; return <div className="screen"><Head title="Sign in" /><SignInForm onDone={() => nav('/app')} /></div> }
